#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Generate and validate the apollo-pack catalog.

The catalog lists every item in the pack: Agent Skills under ``skills/<id>/``
(with metadata in ``SKILL.md`` frontmatter) and host plugins under
``plugins/<id>/`` (with metadata in ``pyproject.toml``). It is written to
``catalog.json`` (machine) and to a fenced block in ``README.md`` (human).

Usage:
    uv run tools/catalog.py build    # write catalog.json and the README block
    uv run tools/catalog.py check    # fail if either artifact has drifted

Output is deterministic: items are sorted by id, JSON is indented with two
spaces and ``ensure_ascii=False``, and there are no timestamps anywhere.
"""

from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "catalog.json"
README = REPO / "README.md"
VERSION_FILE = REPO / "VERSION"

SCHEMA_VERSION = 1
START = "<!-- catalog:start -->"
END = "<!-- catalog:end -->"
GENERATED_NOTE = "<!-- generated by tools/catalog.py; do not edit by hand -->"

TYPES = {"skill", "plugin"}
REQUIRED_FIELDS = ("id", "type", "name", "version", "description", "path", "license")


class CatalogError(Exception):
    """A validation or drift error that should stop the run."""


def pack_version() -> str:
    try:
        text = VERSION_FILE.read_text(encoding="utf-8").strip()
    except FileNotFoundError as exc:
        raise CatalogError("missing VERSION file at the repo root") from exc
    if not text:
        raise CatalogError("VERSION file is empty")
    return text


def parse_frontmatter(skill_md: Path) -> dict[str, Any]:
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise CatalogError(f"{skill_md}: missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise CatalogError(f"{skill_md}: unterminated YAML frontmatter")
    data = yaml.safe_load(text[4:end])
    if not isinstance(data, dict):
        raise CatalogError(f"{skill_md}: frontmatter is not a mapping")
    return data


def collapse(value: Any) -> str:
    return " ".join(str(value).split())


def make_item(
    *,
    item_id: str,
    item_type: str,
    name: Any,
    version: Any,
    description: Any,
    license_value: Any,
    path: str,
    docs: str,
    author: Any = None,
    platforms: Any = None,
    tags: Any = None,
    category: Any = None,
) -> dict[str, Any]:
    item: dict[str, Any] = {
        "id": item_id,
        "type": item_type,
        "name": collapse(name),
        "version": collapse(version),
        "description": collapse(description),
        "path": path,
        "license": collapse(license_value),
    }
    if author:
        item["author"] = collapse(author)
    if platforms:
        item["platforms"] = [collapse(p) for p in platforms]
    if tags:
        item["tags"] = [collapse(t) for t in tags]
    if category:
        item["category"] = collapse(category)
    if docs:
        item["docs"] = docs
    return item


def skill_item(skill_dir: Path) -> dict[str, Any]:
    item_id = skill_dir.name
    fm = parse_frontmatter(skill_dir / "SKILL.md")
    for key in ("name", "description", "version", "license"):
        if not fm.get(key):
            raise CatalogError(f"skills/{item_id}/SKILL.md: missing required field '{key}'")
    if collapse(fm["name"]) != item_id:
        raise CatalogError(
            f"skills/{item_id}: frontmatter name '{collapse(fm['name'])}' "
            f"must match the folder name '{item_id}'"
        )
    hermes = (fm.get("metadata") or {}).get("hermes") or {}
    return make_item(
        item_id=item_id,
        item_type="skill",
        name=fm["name"],
        version=fm["version"],
        description=fm["description"],
        license_value=fm["license"],
        path=f"skills/{item_id}",
        docs=f"skills/{item_id}/SKILL.md",
        author=fm.get("author"),
        platforms=fm.get("platforms"),
        tags=hermes.get("tags"),
        category=hermes.get("category"),
    )


def plugin_item(plugin_dir: Path) -> dict[str, Any]:
    item_id = plugin_dir.name
    pyproject = plugin_dir / "pyproject.toml"
    try:
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise CatalogError(f"plugins/{item_id}: missing pyproject.toml") from exc
    project = data.get("project")
    if not isinstance(project, dict):
        raise CatalogError(f"plugins/{item_id}/pyproject.toml: missing [project] table")
    for key in ("name", "version", "description"):
        if not project.get(key):
            raise CatalogError(f"plugins/{item_id}/pyproject.toml: missing project.{key}")
    license_value = project.get("license")
    if isinstance(license_value, dict):
        license_value = license_value.get("text")
    if not license_value:
        raise CatalogError(f"plugins/{item_id}/pyproject.toml: missing project.license")
    authors = project.get("authors") or []
    author = authors[0].get("name") if authors and isinstance(authors[0], dict) else None
    return make_item(
        item_id=item_id,
        item_type="plugin",
        name=project["name"],
        version=project["version"],
        description=project["description"],
        license_value=license_value,
        path=f"plugins/{item_id}",
        docs=f"plugins/{item_id}/README.md",
        author=author,
        tags=project.get("keywords"),
    )


def collect_items() -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    skills_root = REPO / "skills"
    for skill_dir in sorted(p for p in skills_root.glob("*") if p.is_dir()):
        skill_md = skill_dir / "SKILL.md"
        if skill_md.is_file():
            items.append(skill_item(skill_dir))
    plugins_root = REPO / "plugins"
    for plugin_dir in sorted(p for p in plugins_root.glob("*") if p.is_dir()):
        if (plugin_dir / "pyproject.toml").is_file():
            items.append(plugin_item(plugin_dir))

    seen: dict[str, str] = {}
    for item in items:
        for field in REQUIRED_FIELDS:
            if not item.get(field):
                raise CatalogError(f"item '{item.get('id', '?')}': missing field '{field}'")
        if item["type"] not in TYPES:
            raise CatalogError(f"item '{item['id']}': invalid type '{item['type']}'")
        if item["id"] in seen:
            raise CatalogError(f"duplicate item id '{item['id']}'")
        seen[item["id"]] = item["type"]
        if not (REPO / item["path"]).is_dir():
            raise CatalogError(f"item '{item['id']}': path '{item['path']}' does not exist")
        if not (REPO / item["docs"]).is_file():
            raise CatalogError(f"item '{item['id']}': docs '{item['docs']}' does not exist")

    items.sort(key=lambda it: it["id"])
    return items


def dump_catalog(items: list[dict[str, Any]]) -> str:
    document = {
        "schemaVersion": SCHEMA_VERSION,
        "packVersion": pack_version(),
        "items": items,
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def cell(value: str) -> str:
    return value.replace("|", "\\|")


def render_block(items: list[dict[str, Any]]) -> str:
    lines = [
        START,
        GENERATED_NOTE,
        "",
        "| Name | Type | Version | Description | Path | Docs |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in items:
        docs_name = Path(item["docs"]).name
        lines.append(
            "| {name} | {type} | {version} | {description} | `{path}` | "
            "[{label}]({target}) |".format(
                name=cell(item["name"]),
                type=item["type"],
                version=cell(item["version"]),
                description=cell(item["description"]),
                path=item["path"],
                label=docs_name,
                target=item["docs"],
            )
        )
    lines.append(END)
    return "\n".join(lines)


def extract_block(text: str) -> str:
    if text.count(START) != 1 or text.count(END) != 1:
        raise CatalogError(f"{README.name}: expected exactly one catalog marker pair")
    start = text.index(START)
    end = text.index(END) + len(END)
    if end < start:
        raise CatalogError(f"{README.name}: catalog markers are out of order")
    return text[start:end]


def replace_block(text: str, block: str) -> str:
    existing = extract_block(text)
    return text.replace(existing, block, 1)


def report_diff(label: str, expected: str, actual: str) -> None:
    import difflib

    print(f"drift: {label}", file=sys.stderr)
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=f"{label} (committed)",
        tofile=f"{label} (expected)",
        lineterm="",
    )
    for line in diff:
        print(line, file=sys.stderr)


def cmd_build() -> int:
    items = collect_items()
    catalog_text = dump_catalog(items)
    block = render_block(items)

    current = README.read_text(encoding="utf-8")
    README.write_text(replace_block(current, block), encoding="utf-8")
    CATALOG.write_text(catalog_text, encoding="utf-8")

    print(f"wrote catalog.json and README block ({len(items)} items)")
    return 0


def cmd_check() -> int:
    items = collect_items()
    expected_catalog = dump_catalog(items)
    expected_block = render_block(items)
    failures = 0

    if not CATALOG.is_file():
        print("drift: catalog.json is missing; run 'uv run tools/catalog.py build'", file=sys.stderr)
        failures += 1
    else:
        actual_catalog = CATALOG.read_text(encoding="utf-8")
        if actual_catalog != expected_catalog:
            report_diff("catalog.json", expected_catalog, actual_catalog)
            failures += 1

    readme_text = README.read_text(encoding="utf-8")
    actual_block = extract_block(readme_text)
    if actual_block != expected_block:
        report_diff("README.md catalog block", expected_block, actual_block)
        failures += 1

    if failures:
        print(
            f"catalog check failed ({failures} drift); "
            "run 'uv run tools/catalog.py build'",
            file=sys.stderr,
        )
        return 1
    print(f"catalog check OK ({len(items)} items)")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[1] not in {"build", "check"}:
        print("usage: uv run tools/catalog.py {build|check}", file=sys.stderr)
        return 2
    try:
        if argv[1] == "build":
            return cmd_build()
        return cmd_check()
    except CatalogError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
